### ================= MENU =================
### Ambil semua menu
GET http://localhost:5000/api/menu
Content-Type: application/json

### Tambah menu baru
POST http://localhost:5000/api/menu
Content-Type: application/json

{
  "name": "Chicken Wings",
  "price": 25000,
  "category": "food",
  "photo": "cappuccino.jpg",
  "available": true
}

### Ambil detail menu by ID
GET http://localhost:5000/api/menu/1
Content-Type: application/json

### Update menu by ID
PUT http://localhost:5000/api/menu/1
Content-Type: application/json

{
  "name": "Cappuccino",
  "price": 23000,
  "category": "Coffee",
  "photo": "./src/assets/images/rapi.jpg",
  "available": true
}

### Hapus menu by ID
DELETE http://localhost:5000/api/menu/12
Content-Type: application/json



### ================= ORDERS =================
### Buat pesanan baru
POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "orderId": "MC123512",
  "tableNumber": 12,
  "items": [
    { "id": 10, "quantity": 1, "price": 20000 },
  ],
  "totalPrice": 20000,
  "status": "pending",
  "paymentProof": "bukti.jpg"
}

### Ambil semua orders
GET http://localhost:5000/api/orders
Content-Type: application/json

### Ambil order by orderId
GET http://localhost:5000/api/orders/MC933696
Content-Type: application/json

### Update status order (misal: Paid)
PUT http://localhost:5000/api/orders/ORD12345
Content-Type: application/json

{
  "status": "Paid",
  "payment_proof": "bukti_qris.png"
}

### Hapus order
DELETE http://localhost:5000/api/orders/ORD12345
Content-Type: application/json



### ================= ORDER ITEMS =================
### Ambil semua order items
GET http://localhost:5000/api/order-items
Content-Type: application/json

### Ambil order items by orderId
GET http://localhost:5000/api/order-items/MC933696
Content-Type: application/json

### Tambah order item (manual)
POST http://localhost:5000/api/order-items
Content-Type: application/json

{
  "orderId": "ORD12345",
  "menuId": 2,
  "quantity": 1,
  "subtotal": 30000
}

### Update order item
PUT http://localhost:5000/api/order-items/1
Content-Type: application/json

{
  "quantity": 3,
  "subtotal": 90000
}

### Hapus order item
DELETE http://localhost:5000/api/order-items/1
Content-Type: application/json

###
PATCH http://localhost:5000/api/orders/MC417733/status
Content-Type: application/json

{
  "status": "done"
}

### Toggle menu availability
PATCH http://localhost:5000/api/menu/6
Content-Type: application/json

{
  "available": 0
}

### Get menu by ID
GET http://localhost:5000/api/menu/6